driver:
  name: vagrant
  require_chef_omnibus: true

chef_versions:
- 11
- 12

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: test/encrypted_data_bag_secret_key

platforms:
- name: debian-7.8
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: centos-6.4

suites:
- name: default
  attributes:
    supervisor:
      inet_port: 9001
      inet_credentials_from_data_bag: True
  run_list:
  - recipe[supervisor]
