driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt::default]
  - name: ubuntu-10.04
    run_list:
      - recipe[apt::default]
  - name: centos-6.4
  - name: centos-5.9

suites:
  - name: default
    run_list:
      - recipe[supervisor::default]
  - name: chroot
    run_list:
      - recipe[daemonuser::create-fixtures]
      - recipe[supervisor::default]
    attributes:
      supervisor:
        install:
          virtualenv: /opt/supervisor
          daemon_user: supervisor
          admin_user: root
          admin_group: superadm
