---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5
  - name: ubuntu-12.04
    run_list:
      - apt::default

suites:
  - name: default
    run_list:
      - supervisor::default

  - name: supervisor_program
    run_list:
      - supervisor::default
      - supervisor_program::enable
      - supervisor_program::disable
      - supervisor_program::start
      - supervisor_program::stop
      - supervisor_program::restart
