sudo: required
cache: bundler
language: ruby
services:
  - docker
rvm:
- 2.1.6
env:
  matrix:
  - CHEF_VERSION="11"
  - CHEF_VERSION="12"
  global:
  - USE_SYSTEM_GECODE=true
  - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
before_install:
- curl -o ~/gecode.tar.gz https://poise-gecode.s3.amazonaws.com/gecode-3.7.3-ubuntu12.04-x86_64.tar.gz
- tar xzf ~/gecode.tar.gz -C ~
- rm ~/gecode.tar.gz
- gem install bundler
- bundle config build.dep_selector "--with-cflags=\"-I$HOME/gecode-3.7.3/include\"
  --with-cppflags=\"-I$HOME/gecode-3.7.3/include\" --with-ldflags=\"-L$HOME/gecode-3.7.3/lib
  -Wl,-rpath=$HOME/gecode-3.7.3/lib\""
bundler_args: "--deployment --binstubs"
script:
- "./bin/foodcritic ."
- "./bin/kitchen test -d always"
